# Training-specific configuration for DM-Net Oral Cancer Classification

data:
  batch_size: 32
  augmentation: true
  augmentation_params:
    horizontal_flip: true
    vertical_flip: false
    rotation: 15
    brightness: 0.1
    contrast: 0.1
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

training:
  num_epochs: 50
  learning_rate: 1e-4
  optimizer: "adamw"
  weight_decay: 0.01
  scheduler: "cosine"
  early_stopping_patience: 7
  checkpoint_dir: "checkpoints"
  log_interval: 10
  mixup: false
  mixup_alpha: 0.2
  label_smoothing: 0.1
  
tensorboard:
  enabled: true
  log_dir: "logs"